tinyMCE.addI18n('fr.media_dlg',{
title:"Insérer / éditer média riche",
general:"Géneral",
advanced:"Avancé",
file:"Fichier/URL",
list:"Liste",
size:"Taille",
preview:"Prévisualisation",
constrain_proportions:"Proportions respectées",
type:"Type",
id:"Id",
name:"Nom",
class_name:"Nom de classe",
vspace:"Espace vertical",
hspace:"Espace horizontal",
play:"Lecture automatique",
loop:"Boucle",
menu:"Afficher le menu contextuel",
quality:"Qualité",
scale:"Echelle",
align:"Alignement horizontal",
salign:"Positionement",
wmode:"Opacité",
bgcolor:"Couleur de fond",
base:"Base",
flashvars:"Variables Flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Cache",
hidden:"Masqué",
controller:"Controlleur",
kioskmode:"Kiosk mode",
playeveryframe:"Jouer toutes les images clés",
targetcache:"Cible du cache",
correction:"Aucune correction",
enablejavascript:"Activer le JavaScript",
starttime:"Début",
endtime:"Fin",
href:"Href",
qtsrcchokespeed:"Choke speed",
target:"Cible",
volume:"Volume",
autostart:"Départ automatique",
enabled:"Activé",
fullscreen:"Plein écran",
invokeurls:"Invoquer les URL",
mute:"Muet",
stretchtofit:"Adapter au conteneur",
windowlessvideo:"Vidéo sans fenêtre",
balance:"Equaliseur",
baseurl:"URL racine",
captioningid:"Captioning id",
currentmarker:"Marqueur actuel",
currentposition:"Position actuelle",
defaultframe:"Image par défaut",
playcount:"Nombre de lecture",
rate:"Taux",
uimode:"Mode d'IU",
flash_options:"Options Flash",
qt_options:"Options Quicktime",
wmp_options:"Options Windows media player",
rmp_options:"Options Real media player",
shockwave_options:"Options Shockwave",
autogotourl:"Redirection automatique vers l'URL",
center:"Centre",
imagestatus:"Statut de l'image",
maintainaspect:"Maintenir l'aspect",
nojava:"Pas de java",
prefetch:"Precalcul",
shuffle:"Aléatoire",
console:"Terminal",
numloop:"Nombre de tours",
controls:"Contrôles",
scriptcallbacks:"Rappels de scripts",
swstretchstyle:"Style d'extension",
swstretchhalign:"Extension horizontal",
swstretchvalign:"Extension vertical",
sound:"Son",
progress:"Progression",
qtsrc:"Source QT",
qt_stream_warn:"Les ressources RTSP en flux doivent être ajoutées dans le champ de la source QT sous l'onglet Avancé.\nVous devez aussi ajouter une version originale dans le champ source..",
align_top:"Haut",
align_right:"Droite",
align_bottom:"Bas",
align_left:"Gauche",
align_center:"Centre",
align_top_left:"Haut gauche",
align_top_right:"Haut droit",
align_bottom_left:"Bas gauche",
align_bottom_right:"Bas droit",
flv_options:"Options vidéo en Flash",
flv_scalemode:"Mode ajusté",
flv_buffer:"Tampon",
flv_startimage:"Image de départ",
flv_starttime:"Début",
flv_defaultvolume:"Volume par défaut",
flv_hiddengui:"GUI masqué",
flv_autostart:"Départ auto",
flv_loop:"Boucle",
flv_showscalemodes:"Afficher les modes d'ajustement",
flv_smoothvideo:"Vidéo lissée",
flv_jscallback:"Rappel JS"
});