<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['Happy birthday!'] = 'Feliz cumpleaños!';
$_LANGMAIL['Newsletter confirmation'] = 'Confirmación de la suscripción a nuestro Boletín de noticias';
$_LANGMAIL['Newsletter voucher'] = 'Voucher boletín de noticias';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Enlace a su lista de regalos';
$_LANGMAIL['Message from'] = 'Mensaje de';
$_LANGMAIL['Product quantity'] = 'Cantidad de producto';
$_LANGMAIL['Your cart and your discount'] = 'Su cesta y descuento';
$_LANGMAIL['Thanks for your order'] = '¡Gracias por su pedido!';
$_LANGMAIL['You are one of our best customers'] = 'Gracias por ser uno de nuestros mejores clientes';
$_LANGMAIL['We miss you'] = 'Lo echamos de menos';
$_LANGMAIL['Product available'] = 'Producto disponible';
$_LANGMAIL['Product out of stock'] = 'Uno o más productos están agotados';
$_LANGMAIL['Error reporting from your PayPal module'] = 'Error desde el modulo paypal';
$_LANGMAIL['Congratulations!'] = '¡Felicitaciones!';
$_LANGMAIL['Referral Program'] = 'Programa de referidos';
$_LANGMAIL['A friend sent you a link to'] = 'Un amigo te ha enviado un link';
$_LANGMAIL['Welcome!'] = '¡Bienvenido!';
$_LANGMAIL['Message from contact form'] = 'Mensaje desde el formulario de contacto';
$_LANGMAIL['Your message has been correctly sent'] = 'Su mensaje se ha enviado correctamente';
$_LANGMAIL['New credit slip regarding your order'] = 'Nuevo vale de compra relacionado con su pedido';
$_LANGMAIL['Virtual product to download'] = 'Producto(s) virtual(es) disponibles para descargar';
$_LANGMAIL['Fwd: Customer message'] = 'Fw: Mensaje de cliente';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Su cuenta de invitado se transformó en cuenta de cliente';
$_LANGMAIL['Package in transit'] = 'Paquete en camino';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Log: Tiene una nueva alerta desde su tienda';
$_LANGMAIL['Order confirmation'] = 'Confirmación del pedido';
$_LANGMAIL['Message from a customer'] = 'Mensaje de un cliente';
$_LANGMAIL['New message regarding your order'] = 'Nuevo mensaje relacionado con su pedido';
$_LANGMAIL['Your order return state has changed'] = 'El estado de retorno de su orden ha cambiado';
$_LANGMAIL['Your new admin password'] = 'Tu nueva contraseña de administrador';
$_LANGMAIL['Password query confirmation'] = 'Confirmación de clave';
$_LANGMAIL['An answer to your message is available'] = 'Hay una respuesta a su mensaje';
$_LANGMAIL['New voucher regarding your order'] = 'Nuevo cupon correspondiente a su orden';
$_LANGMAIL['Related Order ID:'] = 'Id del pedido relacionado:';
$_LANGMAIL['Related Product:'] = 'Producto relacionado:';
$_LANGMAIL['Your password'] = 'Tu contraseña';
$_LANGMAIL['New voucher regarding your order #'] = 'Nuevo vale de descuento relacionado con tu pedido #';
