<?php

global $_MODULE;
$_MODULE = array();
$_MODULE['<{twenga}PrestaShop>twenga_6702ebde453c9145652c0b007489904c'] = 'After subscribing please check the email sent by Twenga. If there is still error, contact Twenga customer service.';
$_MODULE['<{twenga}PrestaShop>twenga_da8ac71ff9563d9a5dd0f8894c8bc0ac'] = 'Get your products listed on Twenga.co.uk and follow sales generated by Twenga';
$_MODULE['<{twenga}PrestaShop>twenga_95f01a5bae7b4b64a76372538e4fd315'] = 'E-Merchants country. Use the ISO_3166-1 Alpha-2 country code format.';
$_MODULE['<{twenga}PrestaShop>twengaobj_d00d3f61833c8686be3f0ca7df670e20'] = 'This call to Twenga Web Services failed and returned an HTTP status of %d. This means:';
